# Configuración para la documentación online:
# https://gatovid-api.readthedocs.io/es/latest/
#
# Más sobre el formato:
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

sphinx:
   configuration: docs/src/conf.py

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
