name: Continuous Integration

on:
  pull_request:
  push:
    branches: master

jobs:
  python-tests:
    name: Python tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install full dependencies
        run: |
            docker-compose build
            docker-compose up -d
            docker-compose run api /usr/local/bin/python -m unittest

  python-linter:
      name: Python linter
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.8'
        - name: Install linter
          run: python -m pip install flake8
        - name: Run linter
          run: python -m flake8 .

  python-fmt:
      name: Python formatting
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.8'
        - name: Install formatting tools
          run: python -m pip install black isort
        - name: Run black
          run: python -m black . --check
        - name: Run isort
          run: python -m isort . --check
